In [15]:
#! /usr/bin/python3
import sys
import numpy as np
import pandas as pd

In [34]:
df = pd.read_csv('dados.csv', index_col=None, parse_dates=['Timestamp'])
del(df['Unnamed: 0'])
df.set_index('Timestamp', inplace=True)
df = df[['AirTC', 'RH', 'Rain_mm']]

In [89]:
#mostra na coluna da chuva, onde n ha valores
print(df.Rain_mm[np.isnan(df.Rain_mm)])

Timestamp
2011-12-13 09:10:00   NaN
2011-12-13 09:10:10   NaN
2011-12-13 09:10:20   NaN
2011-12-13 09:10:30   NaN
2011-12-13 09:10:40   NaN
2011-12-13 09:10:50   NaN
2011-12-13 09:11:00   NaN
2011-12-13 09:11:10   NaN
2011-12-13 09:11:20   NaN
2011-12-13 09:11:30   NaN
2011-12-13 09:11:40   NaN
2011-12-13 09:11:50   NaN
2011-12-13 09:12:00   NaN
2011-12-13 09:12:10   NaN
2011-12-13 09:12:20   NaN
2011-12-13 09:12:30   NaN
2011-12-13 09:12:40   NaN
2011-12-13 09:12:50   NaN
2011-12-13 09:55:00   NaN
2011-12-13 09:55:10   NaN
2011-12-13 09:55:20   NaN
2011-12-13 09:55:30   NaN
2011-12-13 09:55:40   NaN
2011-12-13 09:55:50   NaN
Name: Rain_mm, dtype: float64

In [146]:
#df.Rain_mm.index[0]
print("Existem %d NaN's" % (len( df.Rain_mm[np.isnan(df.Rain_mm)])) )

Existem 24 NaN's

In [149]:
# dados.csv          = 259876 linhas
# df.Rain_mm.count() = 259851 

#x=float('nan')
#np.isnan(x)
cnan = 0 #contador para marcar sequencias de nans
i=-1
j=1
for valor in df.Rain_mm:
    i = i + 1
    if np.isnan(valor):
        #print("NaN em: %s %s" % (df.Rain_mm.index[i], valor))
        if (i - j) == 1 :
            j = i            
            print(df.Rain_mm.index[i], cnan)
            
        else:
            j = i
            cnan += 1
            print(df.Rain_mm.index[i],cnan)

2011-12-13 09:10:00 1
2011-12-13 09:10:10 1
2011-12-13 09:10:20 1
2011-12-13 09:10:30 1
2011-12-13 09:10:40 1
2011-12-13 09:10:50 1
2011-12-13 09:11:00 1
2011-12-13 09:11:10 1
2011-12-13 09:11:20 1
2011-12-13 09:11:30 1
2011-12-13 09:11:40 1
2011-12-13 09:11:50 1
2011-12-13 09:12:00 1
2011-12-13 09:12:10 1
2011-12-13 09:12:20 1
2011-12-13 09:12:30 1
2011-12-13 09:12:40 1
2011-12-13 09:12:50 1
2011-12-13 09:55:00 2
2011-12-13 09:55:10 2
2011-12-13 09:55:20 2
2011-12-13 09:55:30 2
2011-12-13 09:55:40 2
2011-12-13 09:55:50 2

[43419,
 43428,
 43432,
 43435,
 43439,
 43442,
 43447,
 43453,
 43459,
 43462,
 43464,
 43465,
 43467,
 43470,
 43473,
 43475,
 43477,
 43478,
 43480,
 43482,
 43483,
 43485,
 43486,
 43488,
 43490,
 43492,
 43495,
 43498,
 43501,
 43505,
 43510,
 43514,
 43522,
 43540,
 43629,
 50029,
 52166,
 99682,
 99724,
 99734,
 99738,
 99742,
 99747,
 99756,
 99761,
 99765,
 99767,
 99769,
 99770,
 99771,
 99773,
 99775,
 99781,
 99787,
 99795,
 99799,
 99806,
 99813,
 99846,
 99888,
 99903,
 99942,
 99992,
 100292,
 100293,
 100294,
 100295,
 100296,
 100297,
 100298,
 100299,
 100300,
 100301,
 100302,
 100303,
 100304,
 100305,
 100306,
 100307,
 100308,
 100309,
 100554,
 100555,
 100556,
 100557,
 100558,
 100559,
 100824,
 104561,
 104565,
 104572,
 104578,
 104595,
 113066,
 113067,
 113070,
 113073,
 113077,
 113308,
 115954,
 115966,
 116037,
 128730,
 128791,
 128795,
 128800,
 128807,
 128998,
 129022,
 129031,
 129034,
 129039,
 129042,
 129045,
 129046,
 129048,
 129049,
 129051,
 129053,
 129055,
 129057,
 129059,
 129060,
 129061,
 129063,
 129065,
 129067,
 129068,
 129071,
 129072,
 129074,
 129076,
 129079,
 129083,
 129086,
 129090,
 129092,
 129100,
 129114,
 129126,
 129145,
 130372,
 136160,
 145139,
 145145,
 145150,
 145153,
 145154,
 145156,
 145157,
 145159,
 145160,
 145161,
 145163,
 145165,
 145170,
 145175,
 145179,
 145184,
 146313,
 146317,
 146319,
 146321,
 146323,
 146326,
 146329,
 146335,
 146341,
 146347,
 146367,
 146393,
 146403,
 146438,
 197464,
 197492,
 197628,
 197873,
 198116,
 201103,
 201137,
 201180,
 201231,
 201305,
 201391,
 202445,
 202926,
 219436,
 219457,
 219473,
 219507,
 219543,
 219650,
 220178,
 220442,
 220453,
 220475,
 220478,
 220483,
 220731,
 220733,
 220736,
 220739,
 220742,
 220749,
 220776,
 220791,
 220804,
 220814,
 220862,
 220867,
 220872,
 220886,
 220943,
 221088,
 221176,
 221184,
 221192,
 221198,
 221208,
 221226,
 221270,
 221304,
 222024,
 224207,
 249508,
 249558,
 249607,
 249704,
 250400,
 251426,
 255560,
 255571,
 255580,
 255594,
 255602,
 255606,
 255610,
 255613,
 255615,
 255617,
 255620,
 255625,
 255629,
 255633,
 255637,
 255641,
 255645,
 255650,
 255655,
 255656,
 255657,
 255658,
 255659,
 255661,
 255662,
 255664,
 255666,
 255668,
 255669,
 255672,
 255675,
 255801,
 256019,
 256024,
 256026,
 256027,
 256028,
 256029,
 256031,
 256033,
 256034,
 256036,
 256037,
 256040,
 256045,
 256058,
 256076,
 256102,
 256392,
 256404,
 256418,
 256516,
 256526,
 256530,
 256535,
 256544,
 256561,
 256569,
 256577,
 256585,
 256592,
 256600,
 256612,
 256638,
 256678,
 256724,
 256773,
 256866,
 256902]